#include "cellmaker.h"
#include "ui_cellmaker.h"
#include <QOpenGLWidget>
#include <QOpenGLFunctions>
#include <QPainter>
#include <QRandomGenerator>
#include <QVector>
#include <QPointF>
#include <QGroupBox>
#include <QSizePolicy>
#include <QtMath>
#include <QWheelEvent>
    #include <QRandomGenerator>
#include <QPainterPath>
#include <QGraphicsPathItem>
#include <QMessageBox>
#include <QFile>
#include <QTextStream>
#include <QStringList>
#include <QFileInfo>
#include <QDir>
#include <QDebug>

cellmaker::cellmaker(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::cellmaker)
{
    ui->setupUi(this);

    ui->lineEdit_6->setText("3");

    ui->lineEdit->setText("30");

    ui->lineEdit_10->setText("10");

    ui->lineEdit_11->setText("0");

    ui->lineEdit_2->setText("100");

    ui->lineEdit_5->setText("20");

    ui->checkBox_3->setChecked(true);
    ui->checkBox_4->setChecked(true);

ui->lineEdit_3->setText("0");

ui->lineEdit_4->setText("0");

ui->comboBox->addItem("Uniform");
    ui->comboBox->addItem("Random");

    ui->comboBox_2->addItem("proton");
    ui->comboBox_2->addItem("neutron");
    ui->comboBox_2->addItem("electron");
    ui->comboBox_2->addItem("alpha");

    ui->lineEdit_7->setText("70");

    ui->comboBox_3->addItem("Disk");
    ui->comboBox_3->addItem("Point");


    ui->lineEdit_8->setText("1");

    ui->lineEdit_9->setText("100");

    ui->comboBox_4->addItem("TISSUE-SOFT(ICRU-44)");
    ui->comboBox_4->addItem("WATER");
    ui->comboBox_4->addItem("BONE-CORTICAL(ICRU-44)");
    ui->comboBox_4->addItem("ADIPOSE-TISSUE");
    ui->comboBox_4->addItem("A-150-PLASTIC");
    ui->comboBox_4->addItem("B-100-PLASTIC");
    ui->comboBox_4->addItem("MUSCLE-SKELETAL");

    ui->comboBox_5->addItem("TISSUE-SOFT(ICRU-44)");
    ui->comboBox_5->addItem("WATER");
    ui->comboBox_5->addItem("BONE-CORTICAL(ICRU-44)");
    ui->comboBox_5->addItem("ADIPOSE-TISSUE");
    ui->comboBox_5->addItem("A-150-PLASTIC");
    ui->comboBox_5->addItem("B-100-PLASTIC");
    ui->comboBox_5->addItem("MUSCLE-SKELETAL");

    ui->comboBox_6->addItem("TISSUE-SOFT(ICRU-44)");
    ui->comboBox_6->addItem("WATER");
    ui->comboBox_6->addItem("BONE-CORTICAL(ICRU-44)");
    ui->comboBox_6->addItem("ADIPOSE-TISSUE");
    ui->comboBox_6->addItem("A-150-PLASTIC");
    ui->comboBox_6->addItem("B-100-PLASTIC");
    ui->comboBox_6->addItem("MUSCLE-SKELETAL");

    ui->comboBox_7->addItem("AIR-DRY-NIST");



    ui->lineEdit_12->setText("10000");
    ui->lineEdit_13->setText("10");







}

cellmaker::~cellmaker()
{
    delete ui;
}



void cellmaker::on_pushButton_5_clicked()
{
        ui->graphicsView->scale(1.1,1.1);
    ui->graphicsView_2->scale(1.1,1.1);
}


void cellmaker::on_pushButton_6_clicked()
{

    ui->graphicsView->scale(0.9,0.9);
    ui->graphicsView_2->scale(0.9,0.9);

}


void cellmaker::phitsScriptGen(const QString &path, const QString &maxcas, const QString &maxbch, const QString sourceType,
                    const QString proj, const QString r0, const QString z0, const QString e0,
                         QList<CompleteCell> cells, double bufH, double majorZ)
{
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        qWarning() << "Failed to open" << path << ":" << f.errorString();
        return;
    }
    QTextStream out(&f);
    out.setRealNumberNotation(QTextStream::FixedNotation);
    out.setRealNumberPrecision(6);

    //header of inp
    out << "[ T i t l e ]" << Qt::endl;
    out << "Generated by Cell Maker Program" << "\n\n";

    out << "[ P a r a m e t e r s ]" << Qt::endl;
    out << "icntl  =  0" << Qt::endl;
    out << "maxcas =  " << maxcas << Qt::endl;
    out << "maxbch =  " << maxbch << "\n\n";

    //source card here, tho it is dynamic for disk and point
    out << "[ S o u r c e ]" << Qt::endl;

    if (sourceType.trimmed().compare(QLatin1String("Point"), Qt::CaseInsensitive) == 0) {
        // Point Source Logic (s-type = 9)
        out << "s-type = 9" << Qt::endl;
        out << "proj = " << proj << Qt::endl;
        out << "dir = all" << Qt::endl;
        out << "r1 = " << r0 << Qt::endl;
        out << "r2 = " << r0 << Qt::endl;
        out << "x0 = 0.00" << Qt::endl;
        out << "y0 = 0.00" << Qt::endl;
        out << "z0 = " << z0 << Qt::endl;
    } else {
        // Default Source Logic (s-type = 1)
        out << "s-type = 1" << Qt::endl;
        out << "proj = " << proj << Qt::endl;
        out << "dir = -1.00" << Qt::endl;
        out << "r0 = " << r0 << Qt::endl;
        out << "x0 = 0.00" << Qt::endl;
        out << "y0 = 0.00" << Qt::endl;
        out << "z0 = " << z0 << Qt::endl;
        out << "z1 = " << z0 << Qt::endl;
    }
    out << "e0 = " << e0 << "\n\n";

    out << "[ M a t e r i a l ]" << Qt::endl;
    out << "mat[1] $TISSUE-SOFT(ICRU-44)" << Qt::endl;
    out << "1000 -10.5 " << Qt::endl;
    out << "6000 -25.6" << Qt::endl;
    out << "7000 -2.7 " << Qt::endl;
    out << "8000 -60.2" << Qt::endl;
    out << "11000 -0.1" << Qt::endl;
    out << "15000 -0.2" << Qt::endl;
    out << "16000 -0.3" << Qt::endl;
    out << "17000 -0.2" << Qt::endl;
    out << "19000 -0.2\n" << Qt::endl;

    out << "mat[2] $WATER" << Qt::endl;
    out << "1000 -11.1" << Qt::endl;
    out << "8000 -88.9\n" << Qt::endl;

    out << "mat[3] $BONE-CORTICAL(ICRU-44)" << Qt::endl;
    out << "1000 -4.7" << Qt::endl;
    out << "6000 -14.4" << Qt::endl;
    out << "7000 -4.2" << Qt::endl;
    out << "8000 -44.6" << Qt::endl;
    out << "11000 -0.1" << Qt::endl;
    out << "12000 -0.2" << Qt::endl;
    out << "15000 -10.5" << Qt::endl;
    out << "16000 -0.3" << Qt::endl;
    out << "20000 -20.9\n" << Qt::endl;

    out << "mat[4] $ADIPOSE-TISSUE" << Qt::endl;
    out << "1000 -11.4" << Qt::endl;
    out << "6000 -59.8" << Qt::endl;
    out << "7000 -0.7" << Qt::endl;
    out << "8000 -27.8" << Qt::endl;
    out << "11000 -0.1" << Qt::endl;
    out << "16000 -0.1" << Qt::endl;
    out << "17000 -0.1\n" << Qt::endl;

    out << "mat[5] $A-150-PLASTIC" << Qt::endl;
    out << "1000 -10.1" << Qt::endl;
    out << "6000 -77.6" << Qt::endl;
    out << "7000 -3.5" << Qt::endl;
    out << "8000 -5.2" << Qt::endl;
    out << "9000 -1.7" << Qt::endl;
    out << "20000 -1.9\n" << Qt::endl;

    out << "mat[6] $B-100-PLASTIC" << Qt::endl;
    out << "1000 -6.5" << Qt::endl;
    out << "6000 -53.7" << Qt::endl;
    out << "7000 -2.1" << Qt::endl;
    out << "8000 -4.4" << Qt::endl;
    out << "9000 -1.5" << Qt::endl;
    out << "20000 -31.8\n" << Qt::endl;

    out << "mat[7] $MUSCLE-SKELETAL" << Qt::endl;
    out << "1000 -10.2" << Qt::endl;
    out << "6000 -12.3" << Qt::endl;
    out << "7000 -3.5" << Qt::endl;
    out << "8000 -72.9" << Qt::endl;
    out << "11000 -0.1" << Qt::endl;
    out << "15000 -0.2" << Qt::endl;
    out << "16000 -0.5" << Qt::endl;
    out << "19000 -0.3\n" << Qt::endl;

    out << "mat[8] $AIR-DRY-NIST" << Qt::endl;
    out << "6000 -0.0124" << Qt::endl;
    out << "7000 -75.5267" << Qt::endl;
    out << "8000 -23.1781" << Qt::endl;
    out << "18000 -1.2827\n\n" << Qt::endl;

    out << "[ S u r f a c e ]" << Qt::endl;

    //nucleus surf section ehere
    int totalCells = cells.size();
    for (int i = 0; i < totalCells; ++i) {
        const auto& cell = cells[i];
        out << QString("%1  ELL  %2 %3 %4  0 0 %5  %6")
                   .arg(cell.nucSurfId, -3)
                   .arg(cell.nx, 8, 'f', 6)
                   .arg(cell.ny, 8, 'f', 6)
                   .arg(cell.nz, 8, 'f', 6)
                   .arg(cell.nrz, 8, 'f', 6)
                   .arg(-cell.nrx, 8, 'f', 6)
            << " $nucleus" << Qt::endl;
    }

    //cell cyto surfaces
    for (int i = 0; i < totalCells; ++i) {
        const auto& cell = cells[i];
        out << QString("%1  ELL  %2 %3 %4  %5 %6 %7  %8")
                   .arg(cell.cellSurfId, -3)
                   .arg(cell.x, 8, 'f', 6)
                   .arg(cell.y, 8, 'f', 6)
                   .arg(cell.z, 8, 'f', 6)
                   .arg(cell.majorX,8,'f',6)
                   .arg(cell.majorY,8,'f',6)
                   .arg(cell.rz, 8, 'f', 6)
                   .arg(-cell.rx, 8, 'f', 6)
            << " $cytoplasm" << Qt::endl;
    }

    //next id
    int nextId = (totalCells * 2) + 1;

    //global Container Box / Plate
    double halfGrid = (cells.last().x) + (cells.first().rx + 20.0);
    int containerId = nextId++;
    out << QString("%1  RPP  %2 %3 %2 %3 0 %4")
               .arg(containerId)
               .arg(-halfGrid)
               .arg(halfGrid)
               .arg(majorZ + bufH) //+5.0 i remove
        << " $ Global Container Box" << Qt::endl;


    //the planes
    int pz_bottom = nextId++; // Equivalent to 11 in your example
    int pz_top    = nextId++; // Equivalent to 12
    out << QString("%1  PZ  -2.0e-5").arg(pz_bottom) << Qt::endl;
    out << QString("%1  PZ  0.0").arg(pz_top)     << Qt::endl;

    int py_p = nextId++; out << QString("%1  PY  0.58").arg(py_p)  << Qt::endl;
    int py_m = nextId++; out << QString("%1  PY -0.58").arg(py_m)  << Qt::endl;
    int px_p = nextId++; out << QString("%1  PX  0.58").arg(px_p)  << Qt::endl;
    int px_m = nextId++; out << QString("%1  PX -0.58").arg(px_m)  << Qt::endl;

    //le void
    out << "4000   SO   500.0 $ Outer Vacuum Boundary" << Qt::endl;

    out << "\n[ C e l l ]" << Qt::endl;

    QString allExcludedSurfaces = "";

    //nuc and cyto pairs
    for (const auto& cell : cells) {
        //nucleus Cell: Material 2 (Inside nucleus surface)
        out << QString("%1  2 -1.27  -%2").arg(cell.nucSurfId, -3).arg(cell.nucSurfId)
            << " $nucleus" << Qt::endl;

        //cytoplasm Cell: Material 1 (Inside cell surface AND above plane, but NOT inside nucleus)
        // Syntax: (-cellSurf pz_top) #nucSurf
        out << QString("%1  1 -1.127 (-%2 %3) #%4")
                   .arg(cell.cellSurfId, -3)
                   .arg(cell.cellSurfId)
                   .arg(pz_top)
                   .arg(cell.nucSurfId)
            << " $cytoplasm" << Qt::endl;

        //build a string of all cell/nuc IDs to subtract them from the container
        allExcludedSurfaces += QString(" #%1 #%2").arg(cell.cellSurfId).arg(cell.nucSurfId);
    }

    out << QString("3000  2 -1.0  (-%1 %2)").arg(containerId).arg(pz_top) << allExcludedSurfaces << Qt::endl;

    //le buffer
    out << QString("3001  2 -1.0 %1 -%2 -%3 %4 -%5 %6").arg(pz_bottom).arg(pz_top).arg(py_p).arg(py_m).arg(px_p).arg(px_m) << Qt::endl;

    out << "4001 8 -0.00129 -4000 " << allExcludedSurfaces << " #3000 #3001" << Qt::endl;
    //the void
    out << "4000  -1  4000" << Qt::endl;


    out << "\n[ E n d ]";

}



void cellmaker::on_pushButton_clicked()
{
    QGraphicsScene *scene = new QGraphicsScene();

    ui->graphicsView->setScene(scene);

    ui->graphicsView->setRenderHint(QPainter::Antialiasing);


    QGraphicsScene *scene2 = new QGraphicsScene();
    ui->graphicsView_2->setScene(scene2);
    ui->graphicsView_2->setRenderHint(QPainter::Antialiasing);

    QRandomGenerator *generator = QRandomGenerator::global();

    //scene->addRect(QRectF(0, 0, 100, 100), pen, brush);
    //scene->addEllipse(QRectF(150, 0, 100, 50, Qt::red, Qt::yellow));
    //scene->addEllipse(150,0,100,50,Qt::red, Qt::yellow);
    //QRectF rect(0, 0, 50, 50); // Rectangle defined by (x, y, width, height)



    QString cellNoString = ui->lineEdit_6->text();
    QString cellSizeString = ui->lineEdit->text();
    QString nucleusSizeString = ui->lineEdit_10->text();
    QString CellPitchString = ui->lineEdit_11->text();

    QString maxcas = ui->lineEdit_12->text();
    QString maxbch = ui->lineEdit_13->text();

    int cellNo = cellNoString.toInt();
    double cellSize = cellSizeString.toDouble();
    double nucleusSize = nucleusSizeString.toDouble();
    double CellPitch = CellPitchString.toDouble();

    QString sourceType = ui->comboBox_3->currentText();

    //ui->textBrowser->insertPlainText(sourceType);


    //int cellNo = 3;
    //double cellSize = 80.0;  //diameter of each cell
    //double nucleusSize = 10.0;  //diameter of nucleus

    QPen cellOutline(Qt::blue);
    QBrush cellFill(Qt::cyan);

    QPen nucleusOutline(Qt::yellow);
    QBrush nucleusFill(Qt::red);

    double spacing = cellSize+ CellPitch;

   // QList<CellData> cellList;
    //int cellCounter = 1;
    QList<CompleteCell> cellList;
    int totalCells = cellNo * cellNo;
    QString majorZString = ui->lineEdit_5->text();

    QString majorXString = ui->lineEdit_3->text();
    QString majorYString = ui->lineEdit_4->text();


    const double majorZ  = majorZString.toDouble();

    const double majorX = majorXString.toDouble();

    const double majorY = majorYString.toDouble();

    double totalGridSize = (cellNo - 1) * spacing;
    double offset = totalGridSize / 2.0;

    int midIndex = cellNo / 2;

    double gridWidth = (cellNo - 1) * spacing;

    double totalSpan = (cellNo - 1) * spacing;
    double halfSpan = totalSpan / 2.0;

    for (int i = 0; i < cellNo; ++i) {
        for (int j = 0; j < cellNo; ++j) {

            //this is to fix assymetry issue for even number of cell n^2
            //double cx = (i * spacing) - (gridWidth / 2.0);
            //double cy = (j * spacing) - (gridWidth / 2.0);

            double cx = (i * spacing) - halfSpan;
            double cy = (j * spacing) - halfSpan;
            // calculate Centered Coordinates
            // This ensures the central cell (i=midIndex, j=midIndex) is at 0,0
           // double cx = (i - midIndex) * spacing;
           // double cy = (j - midIndex) * spacing;
            double cz = 0.0;

            // draw Cytoplasm in QGraphicsScene
            // Note: We subtract cellSize/2.0 to define the top-left corner for Qt
            QRectF cellRect(cx - cellSize / 2.0, cy - cellSize / 2.0, cellSize, cellSize);
            scene->addEllipse(cellRect, cellOutline, cellFill);

            //calculate and Draw Nucleus (Random Position inside cell)
            double theta = 2.0 * M_PI * generator->generateDouble();
            double r = (cellSize / 2.0 - nucleusSize / 2.0) * sqrt(generator->generateDouble());

            double nx = cx + r * cos(theta);
            double ny = cy + r * sin(theta);

            QRectF nucleusRect(nx - nucleusSize / 2.0, ny - nucleusSize / 2.0, nucleusSize, nucleusSize);
            scene->addEllipse(nucleusRect, nucleusOutline, nucleusFill);

            // data for cell cytoplasm
            //CellData c;
            //c.x = cx;
            //c.y = cy;
            //c.z = cz;
            //c.rx = cellSize / 2.0; // radius of minor axis
            //c.rz = majorZ;         // major axis vector magnitude (vertical height)
            //cellList.append(c);
            CompleteCell cc;

            //cytoplasm center (Grid)
            cc.x = cx; //(i - midIndex) * spacing;
            cc.y = cy; //(j - midIndex) * spacing;
            cc.z = cz; //0.0; // Base of the semi-ellipsoid
            cc.rx = cellSize / 2.0;
            cc.rz = majorZ; // Height of the cell
            cc.majorX = majorX;
            cc.majorY = majorY;

            //the following was simple check, issue is cell shape is complex
            //it when nucleus moves up the dome it can fall outside
            /*
            //random nuclues pos.
            //calculate a safe radius for the nucleus center so it doesn't hit the side walls
            double maxLateralOffset = cc.rx - (nucleusSize / 2.0) - 0.00001; // Subtract small epsilon for safety
            theta = 2.0 * M_PI * generator->generateDouble();
            r = maxLateralOffset * sqrt(generator->generateDouble());

            cc.nx = cc.x + r * cos(theta);
            cc.ny = cc.y + r * sin(theta);

            // a safe Z height
            // To keep it inside a semi-ellipsoid, we must ensure it doesn't hit the "dome"
            // For a sphere-like nucleus, we place it in the lower-middle half:
            cc.nrz = nucleusSize / 4.0; // Example vertical radius
            cc.nrx = nucleusSize / 2.0; // Horizontal radius

            // Place nz such that it is always above z=0 and below the dome height
            cc.nz = cc.nrz + (cc.rz * 0.5 * generator->generateDouble());
            */

            cc.nrx = nucleusSize / 2.0;
            cc.nrz = nucleusSize / 4.0; // Example: Nucleus is flatter than cell

            //safe Z for the nucleus
            //above 0 + nrz and below cell height - nrz
            double minNz = cc.nrz + 0.000001;
            double maxNz = cc.rz - cc.nrz - 0.000001;
            cc.nz = minNz + (maxNz - minNz) * generator->generateDouble();

            //safe lateral (XY) offset at this height
            //based on ellipsoid eq: localRx = rx * sqrt(1 - (nz/rz)^2)
            double localCellRx = cc.rx * std::sqrt(1.0 - std::pow(cc.nz / cc.rz, 2));
            double maxLateralOffset = localCellRx - cc.nrx - 0.000001;

            if (maxLateralOffset < 0) maxLateralOffset = 0; // Safety for very small cells

            theta = 2.0 * M_PI * generator->generateDouble();
            r = maxLateralOffset * std::sqrt(generator->generateDouble());

            cc.nx = cc.x + r * std::cos(theta);
            cc.ny = cc.y + r * std::sin(theta);

            // Assign IDs
            cc.cellSurfId = cellList.size() + 1;
            cc.nucSurfId = cc.cellSurfId + (cellNo * cellNo);

            cellList.append(cc);
        }
    }


    QString bufHString = ui->lineEdit_2->text();

     const double minorX  = cellSize;
     const double bufH    = bufHString.toDouble();     //y =cy
     const double cx = 0.0, cy = 0.0;

     QPen   outline(Qt::blue);
     QBrush domeFill(Qt::cyan);

     //top is y = cy - bufH.
     const QRectF bufferRect(cx - minorX, cy - bufH, 2*minorX, bufH);
     auto rectItem = scene2->addRect(bufferRect, outline, QBrush(Qt::yellow));
     rectItem->setZValue(0);

     //semi ellipse -- represenrs cell from side
     const QRectF ellipseRect(cx - minorX, cy - majorZ, 2*minorX, 2*majorZ);
     QPainterPath dome;
     dome.moveTo(cx + minorX, cy);
     dome.arcTo(ellipseRect, 0, 180);     //upper half
     dome.lineTo(cx - minorX, cy);
     dome.closeSubpath();

     auto domeItem = scene2->addPath(dome, outline, domeFill);
     domeItem->setZValue(1);


    //ui->graphicsView_2->fitInView(scene2->itemsBoundingRect(), Qt::KeepAspectRatio);



     QString proj = ui->comboBox_2->currentText();

     QString r0 = ui->lineEdit_8->text();
     QString z0 = ui->lineEdit_9->text();
     QString e0 = ui->lineEdit_7->text();

     //ui->textBrowser->insertPlainText(sourceType);


phitsScriptGen("input.i", maxcas,maxbch,sourceType,proj,r0,z0,e0,cellList, bufH, majorZ);


}



void cellmaker::on_pushButton_4_clicked()
{
    QApplication::quit();
}


void cellmaker::on_pushButton_3_clicked()
{
    QMessageBox::about(this, tr("CellMaker Program"),
                       tr("Generate Cell Arrays for Monte Carlo Radiation Transport Studies.\n"
                          "Developed by: Mehrdad S. Beni and Hiroshi Watabe, RARiS, Tohoku University, JAPAN -- 2025\n"
                          "Version 1.0"));
}


void cellmaker::on_actionQuit_triggered()
{
    on_pushButton_4_clicked();
}


void cellmaker::on_actionAbout_triggered()
{
    on_pushButton_3_clicked();
}


void cellmaker::on_actionGenerate_Cell_Array_triggered()
{
    on_pushButton_clicked();
}


void cellmaker::on_actionZoom_triggered()
{
    on_pushButton_5_clicked();
}



void cellmaker::on_actionZoom_2_triggered()
{
    on_pushButton_6_clicked();
}

