#include "cellmaker.h"
#include "ui_cellmaker.h"
#include <QOpenGLWidget>
#include <QOpenGLFunctions>
#include <QPainter>
#include <QRandomGenerator>
#include <QVector>
#include <QPointF>
#include <QGroupBox>
#include <QSizePolicy>
#include <QtMath>
#include <QWheelEvent>
    #include <QRandomGenerator>
#include <QPainterPath>
#include <QGraphicsPathItem>
#include <QMessageBox>
#include <QFile>
#include <QTextStream>
#include <QStringList>
#include <QFileInfo>
#include <QDir>
#include <QDebug>

cellmaker::cellmaker(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::cellmaker)
{
    ui->setupUi(this);

    ui->lineEdit_6->setText("3");

    ui->lineEdit->setText("30");

    ui->lineEdit_10->setText("10");

    ui->lineEdit_11->setText("0");

    ui->lineEdit_2->setText("100");

    ui->lineEdit_5->setText("20");

    ui->checkBox_3->setChecked(true);
    ui->checkBox_4->setChecked(true);

ui->lineEdit_3->setText("0");

ui->lineEdit_4->setText("0");

ui->comboBox->addItem("Uniform");
    ui->comboBox->addItem("Random");

    ui->comboBox_2->addItem("proton");
    ui->comboBox_2->addItem("neutron");
    ui->comboBox_2->addItem("electron");
    ui->comboBox_2->addItem("alpha");

    ui->lineEdit_7->setText("70");

    ui->comboBox_3->addItem("Disk");
    ui->comboBox_3->addItem("Point");


    ui->lineEdit_8->setText("1");

    ui->lineEdit_9->setText("100");

    ui->comboBox_4->addItem("Soft Tissue");
    ui->comboBox_4->addItem("Water");
    ui->comboBox_4->addItem("TEP");

    ui->comboBox_5->addItem("Soft Tissue");
    ui->comboBox_5->addItem("Water");

    ui->comboBox_6->addItem("Water");
    ui->comboBox_6->addItem("100ppm Boron Water");

    ui->lineEdit_12->setText("10000");
    ui->lineEdit_13->setText("10");







}

cellmaker::~cellmaker()
{
    delete ui;
}



void cellmaker::on_pushButton_5_clicked()
{
        ui->graphicsView->scale(1.1,1.1);
    ui->graphicsView_2->scale(1.1,1.1);
}


void cellmaker::on_pushButton_6_clicked()
{

    ui->graphicsView->scale(0.9,0.9);
    ui->graphicsView_2->scale(0.9,0.9);

}


void phitsScriptGen(const QString &path, const QString &maxcas,const QString &maxbch, const QString sourceType,
                    const QString proj)
{
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        qWarning() << "Failed to open" << path << ":" << f.errorString();
        return;
    }
    QTextStream out(&f);
    out.setRealNumberNotation(QTextStream::FixedNotation);
    out.setRealNumberPrecision(6);
    int source = 0;
    source = sourceType.trimmed().compare(QLatin1String("Point"), Qt::CaseInsensitive) == 0 ? 9 : 1;
    //start here
    out << "[ T i t l e ]" << '\n' <<
        "Generated by Cell Maker Program" << "\n\n" <<

        "[ P a r a m e t e r s ]" << '\n' <<
        "icntl  =  0" << '\n' <<
        "maxcas =  " << maxcas << '\n' <<
        "maxbch =  " << maxbch << '\n' <<
        "file(6) =   phits.out" << "\n\n" <<

        "[ S o u r c e ]" << '\n' <<
        "s-type = " << source << '\n' <<
        "proj = " << proj << '\n'


        << '\n' <<
        "[ E n d ]";
}


void cellmaker::on_pushButton_clicked()
{
    QGraphicsScene *scene = new QGraphicsScene();

    ui->graphicsView->setScene(scene);

    ui->graphicsView->setRenderHint(QPainter::Antialiasing);


    QGraphicsScene *scene2 = new QGraphicsScene();
    ui->graphicsView_2->setScene(scene2);
    ui->graphicsView_2->setRenderHint(QPainter::Antialiasing);

    QRandomGenerator *generator = QRandomGenerator::global();

    //scene->addRect(QRectF(0, 0, 100, 100), pen, brush);
    //scene->addEllipse(QRectF(150, 0, 100, 50, Qt::red, Qt::yellow));
    //scene->addEllipse(150,0,100,50,Qt::red, Qt::yellow);
    //QRectF rect(0, 0, 50, 50); // Rectangle defined by (x, y, width, height)



    QString cellNoString = ui->lineEdit_6->text();
    QString cellSizeString = ui->lineEdit->text();
    QString nucleusSizeString = ui->lineEdit_10->text();
    QString CellPitchString = ui->lineEdit_11->text();

    QString maxcas = ui->lineEdit_12->text();
    QString maxbch = ui->lineEdit_13->text();

    int cellNo = cellNoString.toInt();
    double cellSize = cellSizeString.toDouble();
    double nucleusSize = nucleusSizeString.toDouble();
    double CellPitch = CellPitchString.toDouble();

    QString sourceType = ui->comboBox_3->currentText();

    //ui->textBrowser->insertPlainText(sourceType);


    //int cellNo = 3;
    //double cellSize = 80.0;  //diameter of each cell
    //double nucleusSize = 10.0;  //diameter of nucleus

    QPen cellOutline(Qt::blue);
    QBrush cellFill(Qt::cyan);

    QPen nucleusOutline(Qt::yellow);
    QBrush nucleusFill(Qt::red);

    double spacing = cellSize+ CellPitch;

    for (int i = 0; i < cellNo; ++i) {
        for (int j = 0; j < cellNo; ++j) {

            //center of current cell
            double cx = i * spacing + cellSize / 2.0;
            double cy = j * spacing + cellSize / 2.0;

            //draw cell cyto
            QRectF cellRect(cx - cellSize / 2.0, cy - cellSize / 2.0, cellSize, cellSize);
            scene->addEllipse(cellRect, cellOutline, cellFill);

            //random No. 0 to 2pi
            double theta = 2.0 * M_PI * generator->generateDouble();  //random angle
            double r = (cellSize / 2.0 - nucleusSize / 2.0) * sqrt(generator->generateDouble());
            //sqrt() ensures uniform area distribution

            double nx = cx + r * cos(theta);
            double ny = cy + r * sin(theta);

            //nucl draw
            QRectF nucleusRect(nx - nucleusSize / 2.0, ny - nucleusSize / 2.0, nucleusSize, nucleusSize);
            scene->addEllipse(nucleusRect, nucleusOutline, nucleusFill);
        }
    }


    QString bufHString = ui->lineEdit_2->text();
     QString majorZString = ui->lineEdit_5->text();


     const double majorZ  = majorZString.toDouble();
     const double minorX  = cellSize;
     const double bufH    = bufHString.toDouble();     //y =cy
     const double cx = 0.0, cy = 0.0;

     QPen   outline(Qt::blue);
     QBrush domeFill(Qt::cyan);

     //top is y = cy - bufH.
     const QRectF bufferRect(cx - minorX, cy - bufH, 2*minorX, bufH);
     auto rectItem = scene2->addRect(bufferRect, outline, QBrush(Qt::yellow));
     rectItem->setZValue(0);

     //semi ellipse -- represenrs cell from side
     const QRectF ellipseRect(cx - minorX, cy - majorZ, 2*minorX, 2*majorZ);
     QPainterPath dome;
     dome.moveTo(cx + minorX, cy);
     dome.arcTo(ellipseRect, 0, 180);     //upper half
     dome.lineTo(cx - minorX, cy);
     dome.closeSubpath();

     auto domeItem = scene2->addPath(dome, outline, domeFill);
     domeItem->setZValue(1);


    //ui->graphicsView_2->fitInView(scene2->itemsBoundingRect(), Qt::KeepAspectRatio);



     QString proj = ui->comboBox_2->currentText();

phitsScriptGen("input.i", maxcas,maxbch,sourceType,proj);


}



void cellmaker::on_pushButton_4_clicked()
{
    QApplication::quit();
}


void cellmaker::on_pushButton_3_clicked()
{
    QMessageBox::about(this, tr("CellMaker Program"),
                       tr("Generate Cell Arrays for Monte Carlo Radiation Transport Studies.\n"
                          "Developed by: Mehrdad S. Beni and Hiroshi Watabe, RARiS, Tohoku University, JAPAN -- 2025\n"
                          "Version 1.0"));
}


void cellmaker::on_actionQuit_triggered()
{
    on_pushButton_4_clicked();
}


void cellmaker::on_actionAbout_triggered()
{
    on_pushButton_3_clicked();
}


void cellmaker::on_actionGenerate_Cell_Array_triggered()
{
    on_pushButton_clicked();
}


void cellmaker::on_actionZoom_triggered()
{
    on_pushButton_5_clicked();
}



void cellmaker::on_actionZoom_2_triggered()
{
    on_pushButton_6_clicked();
}

