[ T i t l e ]
Generated by Cell Maker Program

[ P a r a m e t e r s ]
icntl  =  0
maxcas =  10000
maxbch =  10

[ S o u r c e ]
s-type = 1
proj = proton
dir = -1.00
r0 = 1
z0 = 100
z1 = 100
e0 = 70

[ M a t e r i a l ]

[ E n d ]