[ T i t l e ]
Generated by Cell Maker Program

[ P a r a m e t e r s ]
icntl  =  0
maxcas =  10000
maxbch =  10

[ S o u r c e ]
s-type = 1
proj = proton
dir = -1.00
r0 = 1
x0 = 0.00
y0 = 0.00
z0 = 100
z1 = 100
e0 = 70

[ M a t e r i a l ]
mat[1] $TISSUE-SOFT(ICRU-44)
1000 -10.5 
6000 -25.6
7000 -2.7 
8000 -60.2
11000 -0.1
15000 -0.2
16000 -0.3
17000 -0.2
19000 -0.2

mat[2] $WATER
1000 -11.1
8000 -88.9

mat[3] $BONE-CORTICAL(ICRU-44)
1000 -3.4
6000 -15.5
7000 -4.2
8000 -43.5
11000 -0.1
12000 -0.2
15000 -10.3
16000 -0.3
20000 -22.5

mat[4] $ADIPOSE-TISSUE
1000 -11.4
6000 -59.8
7000 -0.7
8000 -27.8
11000 -0.1
16000 -0.1
17000 -0.1

mat[5] $A-150-PLASTIC
1000 -10.1
6000 -77.6
7000 -3.5
8000 -5.2
9000 -1.7
20000 -1.9

mat[6] $B-100-PLASTIC
1000 -6.6
6000 -53.7
7000 -2.1
8000 -3.2
9000 -16.7
20000 -17.7

mat[7] $MUSCLE-SKELETAL
1000 -10.2
6000 -14.3
7000 -3.4
8000 -71.0
11000 -0.1
15000 -0.2
16000 -0.3
17000 -0.1
19000 -0.4

mat[8] $AIR-DRY-NIST
6000 -0.0124
7000 -75.5267
8000 -23.1781
18000 -1.2827


[ S u r f a c e ]
10   ELL  -0.004086 -0.002502 0.001742  0 0 0.000250  -0.000500 $nucleus
11   ELL  -0.002148 0.000514 0.000295  0 0 0.000250  -0.000500 $nucleus
12   ELL  -0.002854 0.003827 0.001253  0 0 0.000250  -0.000500 $nucleus
13   ELL  0.000179 -0.002715 0.001396  0 0 0.000250  -0.000500 $nucleus
14   ELL  0.000592 0.000057 0.000824  0 0 0.000250  -0.000500 $nucleus
15   ELL  0.000346 0.003675 0.001397  0 0 0.000250  -0.000500 $nucleus
16   ELL  0.004133 -0.003264 0.000490  0 0 0.000250  -0.000500 $nucleus
17   ELL  0.003594 0.000675 0.000728  0 0 0.000250  -0.000500 $nucleus
18   ELL  0.003021 0.003579 0.001463  0 0 0.000250  -0.000500 $nucleus
1    ELL  -0.003868 -0.002528 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
2    ELL  -0.002993 0.000368 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
3    ELL  -0.002736 0.003925 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
4    ELL  0.000683 -0.002927 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
5    ELL  0.000175 0.000792 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
6    ELL  0.000336 0.003841 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
7    ELL  0.003947 -0.002899 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
8    ELL  0.003489 0.000764 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
9    ELL  0.003389 0.003869 0.000000  0.000000 0.000000 0.002000  -0.001500 $cytoplasm
19  RPP  -0.00688914 0.00688914 -0.00688914 0.00688914 0 0.012 $buffer
20  PZ  -2.0e-5
21  PZ  0.0
22  PY  0.58
23  PY -0.58
24  PX  0.58
25  PX -0.58
4000   SO   500.0 $outer boundary

[ C e l l ]
10   1 -1.06  -10 $nucleus
1    1 -1.06 (-1 21) #10 $cytoplasm
11   1 -1.06  -11 $nucleus
2    1 -1.06 (-2 21) #11 $cytoplasm
12   1 -1.06  -12 $nucleus
3    1 -1.06 (-3 21) #12 $cytoplasm
13   1 -1.06  -13 $nucleus
4    1 -1.06 (-4 21) #13 $cytoplasm
14   1 -1.06  -14 $nucleus
5    1 -1.06 (-5 21) #14 $cytoplasm
15   1 -1.06  -15 $nucleus
6    1 -1.06 (-6 21) #15 $cytoplasm
16   1 -1.06  -16 $nucleus
7    1 -1.06 (-7 21) #16 $cytoplasm
17   1 -1.06  -17 $nucleus
8    1 -1.06 (-8 21) #17 $cytoplasm
18   1 -1.06  -18 $nucleus
9    1 -1.06 (-9 21) #18 $cytoplasm
3000  1 -1.06  (-19 21) #1 #10 #2 #11 #3 #12 #4 #13 #5 #14 #6 #15 #7 #16 #8 #17 #9 #18
3001  1 -1.06 20 -21 -22 23 -24 25
4001 8 -0.001290 -4000  #1 #10 #2 #11 #3 #12 #4 #13 #5 #14 #6 #15 #7 #16 #8 #17 #9 #18 #3000 #3001
4000  -1  4000

[ T - Gshow ]
title = generated cell array
mesh =  xyz
x-type = 2
xmin = -0.006889
xmax = 0.006889
nx = 200
y-type = 2
ymin = -0.006889
ymax = 0.006889
ny = 200
 z-type = 1
nz = 1
0.000 0.000300
axis = xy
file = geometry_topview.out
output = 6
epsout = 1

[ T - Track ]
title = track on cell array
mesh =  xyz
x-type = 2
xmin = -0.006889
xmax = 0.006889
nx = 200
y-type = 2
ymin = -0.006889
ymax = 0.006889
ny = 200
 z-type = 1
nz = 1
0.000 0.012000
axis = xy
file = tracks.out
e-type = 3
emin = 1.0E-3
emax = 70
ne = 1
part = all
material = all
epsout = 1

[ T - Deposit ]
title = dose on cell array
mesh =  xyz
x-type = 2
xmin = -0.006889
xmax = 0.006889
nx = 200
y-type = 2
ymin = -0.006889
ymax = 0.006889
ny = 200
 z-type = 1
nz = 1
0.000 0.012000
axis = xy
file = top_view_deposit.out
part = all
material = all
output = dose
unit = 2
epsout = 1

[ T - Deposit ]
title = dose in cell constituents
mesh = reg
reg =  1 10 2 11 3 12 4 13 5 14 6 15 7 16 8 17 9 18
volume
reg      vol
1   9.163e-09
10   2.618e-10
2   9.163e-09
11   2.618e-10
3   9.163e-09
12   2.618e-10
4   9.163e-09
13   2.618e-10
5   9.163e-09
14   2.618e-10
6   9.163e-09
15   2.618e-10
7   9.163e-09
16   2.618e-10
8   9.163e-09
17   2.618e-10
9   9.163e-09
18   2.618e-10
axis = reg
file = dose_cells.out
unit = 0
part = photon neutron proton alpha
material = all
output = dose
epsout = 0

[ E n d ]